# Generated by Django 5.2.12 on 2026-03-21 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('daily_generation_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('audio_url', models.URLField()),
                ('genre', models.CharField(choices=[('POP', 'Pop'), ('ROCK', 'Rock'), ('JAZZ', 'Jazz'), ('RNB', 'R&B'), ('CLASSICAL', 'Classical'), ('COUNTRY', 'Country'), ('HIPHOP', 'Hip-Hop'), ('EDM', 'EDM')], max_length=20)),
                ('mood', models.CharField(choices=[('HAPPY', 'Happy'), ('SAD', 'Sad'), ('ENERGETIC', 'Energetic'), ('CALM', 'Calm'), ('ROMANTIC', 'Romantic')], max_length=20)),
                ('occasion', models.CharField(choices=[('BIRTHDAY', 'Birthday'), ('PARTY', 'Party'), ('WEDDING', 'Wedding'), ('WORKOUT', 'Workout'), ('RELAXATION', 'Relaxation'), ('MOURNING', 'Mourning'), ('ANNIVERSARY', 'Anniversary')], max_length=20)),
                ('voice_tone', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('CHILD', 'Child')], max_length=20)),
                ('generation_status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music.library')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music.user')),
            ],
        ),
        migrations.AddField(
            model_name='library',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='library', to='music.user'),
        ),
    ]
