# Generated by Django 5.2.12 on 2026-04-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='generation_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('TEXT_SUCCESS', 'Text Success'), ('FIRST_SUCCESS', 'First Success'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=20),
        ),
    ]
