# Generated by Django 5.2.12 on 2026-03-21 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_share_link_alter_song_audio_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='share_link',
        ),
    ]
